import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import Header from "sections/header";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Abrar Barbhuyia</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center bg-neutral-200">
        <div className="mx-auto flex h-full w-full max-w-7xl flex-col justify-center px-4">
          <Header />
        </div>
      </main>
    </>
  );
};

export default Home;
